import { useState } from "react";
import api from "../services/api";

import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";

export default function RepositoryReview({ repository }) {

    const [review, setReview] = useState("");
    const [loading, setLoading] = useState(false);

    const generateReview = async () => {

        if (!repository) return;

        try {

            setLoading(true);

            const response = await api.post(
                "/review",
                {
                    repository,
                }
            );

            setReview(response.data.review);

        } catch (error) {

            console.error(error);

            setReview(
                "❌ Failed to generate repository review."
            );

        } finally {

            setLoading(false);

        }

    };

    return (

        <div className="bg-white rounded-xl shadow-xl p-8 mt-8">

            {/* Header */}

            <div className="flex justify-between items-center mb-8">

                <div>

                    <h2 className="text-3xl font-bold">
                        🤖 AI Code Review
                    </h2>

                    <p className="text-gray-500 mt-2">
                        AI-powered repository analysis and code quality review.
                    </p>

                </div>

                <span className="bg-purple-100 text-purple-700 px-4 py-2 rounded-full font-semibold">
                    Generated by Gemini
                </span>

            </div>

            {/* Generate Button */}

            <button
                onClick={generateReview}
                disabled={loading || !repository}
                className="bg-purple-600 hover:bg-purple-700 disabled:bg-gray-400 text-white px-6 py-3 rounded-lg font-semibold transition-all duration-300 hover:shadow-lg"
            >
                {loading
                    ? "🤖 Reviewing Repository..."
                    : "🚀 Generate AI Review"}
            </button>

            {/* Loading */}

            {loading && (

                <div className="mt-8 bg-purple-50 border border-purple-200 rounded-xl p-6">

                    <div className="animate-pulse">

                        <p className="font-semibold text-purple-700">
                            🤖 Gemini is analyzing your repository...
                        </p>

                        <p className="text-gray-600 mt-2">
                            Inspecting architecture...
                        </p>

                        <p className="text-gray-600">
                            Checking code quality...
                        </p>

                        <p className="text-gray-600">
                            Looking for improvements...
                        </p>

                    </div>

                </div>

            )}

            {/* Review */}

            {review && !loading && (

                <div className="mt-8 bg-slate-50 rounded-xl border p-8">

                    <div className="flex justify-between items-center mb-6">

                        <h3 className="text-2xl font-bold">
                            📋 Review Report
                        </h3>

                        <span className="bg-green-100 text-green-700 px-3 py-1 rounded-full text-sm font-semibold">
                            AI Generated
                        </span>

                    </div>

                    <div className="prose prose-lg max-w-none">

                        <ReactMarkdown
                            remarkPlugins={[remarkGfm]}
                        >
                            {review}
                        </ReactMarkdown>

                    </div>

                </div>

            )}

            {/* Empty State */}

            {!review && !loading && (

                <div className="mt-8 text-center bg-slate-50 rounded-xl border p-10">

                    <div className="text-6xl mb-4">
                        🤖
                    </div>

                    <h3 className="text-xl font-semibold">
                        No AI Review Yet
                    </h3>

                    <p className="text-gray-500 mt-3">
                        Click the button above to let Gemini review your repository.
                    </p>

                </div>

            )}

        </div>

    );

}